### ISSUE TITLE
Allow for entries into YAML

### ISSUE THREAD

**Issue by rk-kontur** [fez-github/obsidian-multi-tag#1]
Hi,

this is GREAT, I am looking for something to manipulate notes in exactly this way - based on folders and subfolders.

However, I do never use **inline tags**: I consider them messy and especially placing them at the bottom of my notes is a usecase I do not like. The tag would - in the case of developing notes - sit somewhere more or less randomly at the position of development at the time of placement.

Is it possible to 

1. either manipulate YAML directly, including all properties. I could imagine this being an addition to the existing use case (maybe a little dropdown menu entry above the tag insertion field that directy functionality towards either note text or YAML) Here, adding to existing tags or overwriting them could be a potential issue.
2. integrate the function directly into the Tag Wrangler plugin that already addresses manipulation of tags based on tags themselves. It currently does not offer adding tags to files and does (yet) not allow manipulation based on folders.

THANK YOU so much for FINALLY creating something in the way I long for since I don't know when....

**Comment by technohiker** [comment]
Hello,

Thank you for using my plugin!  I'm happy it's been of use.  I did have YAML listed as a todo, but I hadn't looked back on this plugin for a bit, so your comment brought it back to my attention.  I've been using the Linter plugin to automatically add inline tags to YAML, which could suffice.  Linter can be used in all notes in a folder, but doesn't have the Multi-Select support for notes outside of a folder.  I'll look into adding the YAML functionality myself.

With the introduction of Properties in Obsidian, I'm getting a lot of thoughts about refactoring this to also allow the user to add Properties to multiple notes as well.  You do bring up an interesting point of trying to implement this into Tag Wrangler, which I may also think about.  I've got a lot of ideas for where I could take this plugin.  Can't promise anything soon, but I'll be looking into it.

**Comment by sagewaters** [comment]
@fez-github: Make great use of the plugin as it is now. That said, the ability to assign the same YAML data (Properties) to multiple notes, within a folder or otherwise, would be **very** useful.

**Comment by technohiker** [comment]
@sagewaters @rk-kontur This is now implemented in the 0.8.0 release!  Go into Multi Tag's settings and you'll be able to toggle between YAML and Inline tags.  I only just published the release so it's not available through Community Plugins at the time of this posting, but the functionality is in.

**Comment by zzh1ad** [comment]
@fez-github I use the 0.8.0 release. When I add tags with YAML, the tag will add to YAML and Inline both. 

like this:
![image](https://github.com/fez-github/obsidian-multi-tag/assets/28721263/2ce68121-921e-4a17-9d2f-1b1926bd33e1)

**Comment by feedhopper** [comment]
Oh WOW!

This is GREAT!!!!

Thank you very much!

**Comment by technohiker** [comment]
@zzh1ad That was a silly oversight on my end.  I had both the inline and YAML functions running in one specific condition.  Just patched it up, should be resolved in 0.8.1.

**Comment by technohiker** [comment]
I just realized there may be another bug.  The DEFAULT_SETTINGS variable is set to "inline", but the default Settings option is displayed as YAML, and may not update until you change the selection in Settings for the first time.  I'm unable to test this until much later today, so please take a look at your data.json files within the plugin and make sure it matches what you want.  It'll generate after making your first change to the settings.

Sorry about all the issues.  Will fix them when I can.

**Comment by feedhopper** [comment]
Thanks for hunting the bugs!!


Things like this just happen. I tried with a folder containing ot too many files, so no great harm came from that.

I checked the JSON but found the setting to be YAML.
So I guess it wasn't that...

**Comment by technohiker** [comment]
The bugs I've mentioned before have been addressed, and I've now included an additional toggle in the tag form itself for switching between YAML/Inline.  This is in the 0.9.0 release that was just published.

Since the original issue has been addressed, I will be closing this topic.
