### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by feedhopper** [fez-github/obsidian-multi-tag#4]
I tried adding a tags like

author: davinci

and this had no effect at all.

the same goes for trying to just tag with 

davinci

AM I doing something wrong?

**Comment by feedhopper** [comment]
Oh. I just found out: it DID have an effect. 
I had selected "YAML" but the tags (several attempts) have been put to the bottom of my documents as inline tags

**Comment by technohiker** [comment]
I already addressed this bug in an earlier release, but before I close this topic, are you still having this issue?
