### ISSUE TITLE
BUG: Plugin changes how links are displayed

### ISSUE THREAD

**Issue by CoffeaUrbana** [fez-github/obsidian-multi-tag#6]
Behaviour:
When I activate this plugin, all links in notes receive a box frame with shade:
![grafik](https://github.com/fez-github/obsidian-multi-tag/assets/125163430/442b7c3f-c67e-49e6-9f1a-cde57e41ffac)

Expected behaviour:
The multi properties plugin should not affect how links are displayed in notes.

Thanks for your plugin!

**Comment by technohiker** [comment]
What CSS styling are you using?  I don't use any custom styling in Obsidian, so I don't get any box frames like that at all.  My plugin shouldn't be doing anything to styling.  It probably won't solve the issue, but does turning the plugin off do anything?  I must admit, I'm puzzled as to how my plugin could be affecting this.  

When you say "when I activate this plugin", do you mean turning the plugin on changed the link to that styling?  Or did this occur once you submitted the form for adding tags/props to a note?  In addition, is that link you're showing just for your Property, or are links that are in the note itself being displayed like that?

Lastly, is this for Multi Tag, or Multi Properties?  You mentioned Properties, yet you posted this issue in Multi Tag.

**Comment by CoffeaUrbana** [comment]
I don't use any custom CSS for links, I have the ITS Scheme installed, but even when switching to standard theme the box appears.
Turning your plugin off reverts links to be shown as usual inline text, which is why I figured it could be your plugin.

I had not yet used the functions of your plugin when this occured - just by turning it on the styling changed.

It is for Multi Properties, I mixed that up somehow, sorry.

I switched every other plugin off to be sure, but only switching Multi Properties off and on would have an impact on this styling.

**Comment by technohiker** [comment]
OK, I just found the issue.  My styles.css file was set up so it would affect any <a> element in Obsidian.  I must've been under the impression that it would've only affected the forms I created, but that wasn't the case.  I never noticed because I never used any links in the test notebook I was using.

I'll push an update tomorrow.  It's late right now and I don't want to rush a bug fix, even if it's something simple.    I've also been working on other small updates, so I'll upload them all tomorrow.

If you want to try it out in advance anyway, go to the styles.css file and replace 
```

/* Basic button styling */
a {
	display: inline-block;
	padding: var(--size-4-1) var(--size-4-2);
	text-decoration: none;
	background-color: var(--interactive-normal);
	box-shadow: var(--input-shadow);
	color: var(--text-normal);
	border-radius: 4px; /* Rounded corners */
	cursor: pointer;
	text-align: center;
	font-weight: var(--input-font-weight);
	font-size: var(--font-ui-small);
}

/* Hover and focus styles */
a:hover,
a:focus {
	outline: grey solid 2px;
}

input[type="checkbox"] {
	cursor: pointer;
	position: relative;
	top: 6px;
}

/* Disabled style */
a:disabled {
	background-color: #ccc; /* Disabled background color */
	border-color: #ccc; /* Disabled border color */
	color: #999; /* Disabled text color */
	cursor: not-allowed;
}
```
with...
```
/* Basic button styling */
.modal a {
	display: inline-block;
	padding: var(--size-4-1) var(--size-4-2);
	text-decoration: none;
	background-color: var(--interactive-normal);
	box-shadow: var(--input-shadow);
	color: var(--text-normal);
	border-radius: 4px; /* Rounded corners */
	cursor: pointer;
	text-align: center;
	font-weight: var(--input-font-weight);
	font-size: var(--font-ui-small);
}

/* Hover and focus styles */
.modal a:hover,
.modal a:focus {
	outline: grey solid 2px;
}

.modal input[type="checkbox"] {
	cursor: pointer;
	position: relative;
	top: 6px;
}

/* Disabled style */
.modal a:disabled {
	background-color: #ccc; /* Disabled background color */
	border-color: #ccc; /* Disabled border color */
	color: #999; /* Disabled text color */
	cursor: not-allowed;
}
```
